# 1 工作流名称
name: Build and Deploy

# 2 工作流执行名称
run-name: ${{ github.actor }} is update repo, start building...
# 3 触发器
on:
  # Runs on pushes targeting the default branch 触发推送目标默认分支
  push:
    branches: ["master"]

  # 允许您从 Actions 选项卡手动运行此工作流
  workflow_dispatch:

# 4 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 工作集
jobs:
  # 任务名称 1
  build-and-deploy:
    # 执行平台
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    # 任务步骤
    steps:
      - name: Checkout code (检出代码)
        uses: actions/checkout@v3

      # 安装依赖
      - name: Install dependencies (安装依赖)
        run: npm install
       # 构建项目
      - name: Build (构建)
        run: npm run build:pre

      # 上传构建产物（actions/upload-artifact@v3 会上传工作流程中的文件）
      - name:  Upload build artifacts (上传构建产物)
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist"

     # 部署 GitHub Pages
      - name: Deploy to GitHub Pages(部署到 GitHub Pages)
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
